name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.11

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  dockerBuildAndPublish:
    runs-on: ubuntu-latest
    needs: buildAndTest
    steps:
    - uses: actions/checkout@v3
    - id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-first-image:${{ steps.vars.outputs.sha_short }}
